### ISSUE TITLE
No acess in my region

### ISSUE THREAD

**Issue by Meowcat285** [Accenture/ULAPPH-Cloud-Desktop#68]
No acces in my region with the error: [U99999i] ERROR: Hi US.ca.pleasanton.user! Access from your country (US) region (ca) city (pleasanton) is not allowed at this time.

**Comment by edwindvinas** [comment]
Added US as one of countries allowed to access ulapph-sites, ulapph-portal and ulapph-net. Let me know if these are not the sites you tried to access. Please check back after 30 minutes from now.
